### ISSUE TITLE
Cli testing - adriatic

### ISSUE THREAD

**Issue by adriatic** [monterey-framework/cli#21]
___This issue is a copy of https://github.com/monterey-framework/cli/issues/20 - where tests are done by me, and could be done in a consecutive sections, not interrupted by other people doing the same tests.___
***
## versions
Node: v6.3.1
NPM: 4.0.5

## Todo list
- [ ] lodash
- [ ] **[jquery](https://github.com/monterey-framework/cli/issues/21#issuecomment-269247120)**
- [ ] **[sweetalert](https://github.com/monterey-framework/cli/issues/21#issuecomment-269247935)**
- [ ] toastr
- [ ] **[font-awesome](https://github.com/monterey-framework/cli/issues/21#issuecomment-269220540)**
- [ ] jquery-ui
- [ ] **[flatpickr](https://github.com/monterey-framework/cli/issues/21#issuecomment-269232192)**
- [ ] humane.js
- [ ] mdl
- [ ] **[d3](https://github.com/monterey-framework/cli/issues/21#issuecomment-269087865)**
- [ ] **[dragula](https://github.com/monterey-framework/cli/issues/21#issuecomment-269087459)**
***
### Source code for all tests are maintained in https://github.com/adriatic/cli-importer-tests

**Comment by adriatic** [comment]
Starting from the and: **dragula**

**Comment by adriatic** [comment]
### d3
**Command:** 
`au install d3 --debug`

**Output:**

**What configuration did the importer add to aurelia.json?**

**What code was used to test whether the package is usable?**

**Does it work?**

**In case of failure, what is the expected configuration?**

**Comment by adriatic** [comment]
### font-awesome
**Command:** 
`au install font-awesome --debug`

**Output:**
```
λ au install font-awesome --debug
INFO [Package-installer] Using 'npm' to install the package(s). You can change this by setting the 'packageManager' property in the aurelia.json file to 'npm' or 'yarn'.
INFO [Package-installer] *********** INSTALLING PACKAGES ***********
aurelia-app-font-awesome@0.1.0 C:\work\monterey-framework\cli-importer-tests\aurelia-app-font-awesome
`-- font-awesome@4.7.0

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
INFO [Install] The packages were successfully installed. Going to import them now.
INFO [Importer] *********** Configuring font-awesome ***********
DEBUG [Metadata] There is no "aurelia"."import" section in the package.json file of the plugin (looked in "C:\work\monterey-framework\cli-importer-tests\aurelia-app-font-awesome\node_modules\font-awesome\package.json")
DEBUG [Importer] [SKIP] The "Metadata Strategy" strategy declined configuration
DEBUG [Custom-importer] The plugin does not have a custom importer module. Looked for "C:\work\monterey-framework\cli-importer-tests\aurelia-app-font-awesome\node_modules\font-awesome\importer-callbacks.js"
DEBUG [Importer] [SKIP] The "Custom Importer Strategy" strategy declined configuration
DEBUG [Registry] The registry does not contain a package configuration for font-awesome
DEBUG [Importer] [SKIP] The "Registry Strategy" strategy declined configuration
DEBUG [JSPM] There is no "jspm" section in the package.json file of the plugin (looked in 'C:\work\monterey-framework\cli-importer-tests\aurelia-app-font-awesome\node_modules\font-awesome\package.json')
DEBUG [Importer] [SKIP] The "JSPM Section Strategy" strategy declined configuration
DEBUG [Browser] There is no (usable) "browser" section in the package.json file of the plugin (looked in 'C:\work\monterey-framework\cli-importer-tests\aurelia-app-font-awesome\node_modules\font-awesome\package.json')
DEBUG [Importer] [SKIP] The "Browser Section Strategy" strategy declined configuration
INFO [Importer] [OK] Going to execute the "Amodrotrace Strategy" strategy
ERROR [Importer] An error occurred during the exection of the "Amodrotrace Strategy" importer strategy
ERROR [Importer] TypeError: Cannot read property 'replace' of undefined
DEBUG [Tutorial] There is no tutorial in the package.json of "font-awesome"
DEBUG [Tutorial] There is no tutorial for "font-awesome" (version 4.7.0)
INFO [Importer] *********** Finished configuring font-awesome ***********
```

**What configuration did the importer add to aurelia.json?**

**What code was used to test whether the package is usable?**

**Does it work?**

**In case of failure, what is the expected configuration?**

**Comment by adriatic** [comment]
### flatpickr
**Command:** 
`au install flatpickr --debug`

**Output:**

**What configuration did the importer add to aurelia.json?**

**What code was used to test whether the package is usable?**

**Does it work?**

**In case of failure, what is the expected configuration?**

**Comment by adriatic** [comment]
### jquery
**Command:** 
`au install jquery --debug`

**Output:**

**What configuration did the importer add to aurelia.json?**

**What code was used to test whether the package is usable?**

**Does it work?**

**In case of failure, what is the expected configuration?**

**Comment by adriatic** [comment]
### sweetalert
**Command:** 
`au install sweetalert --debug`

**Output:**

**What configuration did the importer add to aurelia.json?**

**What code was used to test whether the package is usable?**

**Does it work?**

**In case of failure, what is the expected configuration?**

**Comment by JeroenVinke** [comment]
@adriatic sweetalert has been tested by @Thanood. More in https://github.com/monterey-framework/cli/issues/25

**Comment by adriatic** [comment]
I was planning to test them all, independent of others.

**Comment by Thanood** [comment]
```json
          {
            "name": "flatpickr",
            "path": "../node_modules/flatpickr/dist",
            "main": "flatpickr",
            "resources": [
              "flatpickr.css"
            ]
          }
```

> I would like to understand how is the above shown added data to aurelia.json file used by the module loader (RequireJS).

I will try to explain but a lot of "magic" is applied by amodro-trace with which I don't have any experience (I've read the `README` though).
As you probably know, `requirejs` (AMD) modules are defined like this:

```javascript
define('optional-module-name', ['some', 'dependencies'], function(some, dependencies) {
  var myModuleDefinition = {
    aProperty: 'value',
    aMethod: function() {}
  };
  return myModuleDefinition;
});
```

In the case of `flatpickr` (which looks like a CommonJS module), amodro-trace wraps it in an AMD module with module-name: `flatpickr/flatpickr`.

The first line of the `aurelia.json` config (`"name": "flatpickr"`) wraps this module in another module with module-name `flatpickr`. This wrapper module has the following body:

```javascript
define('flatpickr', ['flatpickr/flatpickr'], function (main) { return main; });
```

This is a valid AMD module which does the following:
- the module is called "flatpickr"
- it depends on `flatpickr/flatpickr' generated by amodro-trace from the `flatpickr` source
- `flatpickr/flatpickr' is "injected" as variable `main` into the module definition
- `main` is returned which ultimately means the module `flatpickr` *is*  `flatpickr/flatpickr`

The second and third lines in `aurelia.json` config (`"path": "../node_modules/flatpickr/dist", "main": "flatpickr"`) are used by amodro-trace to fetch the correct source and produce the aforementioned `flatpickr/flatpickr` module.

The `resources` line produces another AMD module which looks like this (abbreviated):

```javascript
define('text!flatpickr/flatpickr.css', ['module'], function(module) {
 module.exports = "the css";
});
```

The module name is prefixed by `text!` which implies that it is loaded by the text loader plugin.
TBH I never used AMD in this way so I can only guess what happens but here is how you would "normally" use the text plugin as an AMD dependency:

```javascript
define('my-module', ['text!./my-module.css'], function (myCss) {
  do.something.with(myCss); // <-- myCss is plain text, containing the style definitions
});
```

Here's the guess:
When you do `<require from="flatpickr/flatpickr.css">`, Aurelia known that this must be loaded by the `text` loader plugin. So the AMD loader does (something like) the following:

```javascript
require('text!flatpickr/flatpickr.css')
```

This is both the module name and implies loading by the `text` plugin.

**Comment by adriatic** [comment]
Thanks, @Thanood - all such bits of data will be collected and organized for a good use.

**Comment by adriatic** [comment]
### aurelia-kendoui-bridge
**Command:** 
`au install aurelia-kendoui-bridge --debug`

**Output:**
```
λ au install aurelia-kendoui-bridge --debug
INFO [Package-installer] Using 'npm' to install the package(s). You can change this by setting the 'packageManager' property in the aurelia.json file to 'npm' or 'yarn'.
INFO [Package-installer] *********** INSTALLING PACKAGES ***********
aurelia-app-kendo@0.1.0 C:\work\monterey-framework\cli-importer-tests\aurelia-app-kendo
`-- aurelia-kendoui-bridge@1.0.1

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
INFO [Install] The packages were successfully installed. Going to import them now.
INFO [Importer] ---------------------------------------------------------
INFO [Importer] *********** Configuring aurelia-kendoui-bridge ***********
DEBUG [Metadata] There is no "aurelia"."import" section in the package.json file of the plugin (looked in "node_modules\aurelia-kendoui-bridge\package.json")
DEBUG [Importer] [SKIP] The "Metadata Strategy" strategy declined configuration
DEBUG [Custom-importer] The plugin does not have a custom importer module. Looked for "node_modules\aurelia-kendoui-bridge\importer-callbacks.js"
DEBUG [Importer] [SKIP] The "Custom Importer Strategy" strategy declined configuration
DEBUG [Registry] The registry does not contain a package configuration for aurelia-kendoui-bridge
DEBUG [Importer] [SKIP] The "Registry Strategy" strategy declined configuration
INFO [Importer] [OK] Going to execute the "JSPM Section Strategy" strategy
INFO [Importer] *********** Finished configuring aurelia-kendoui-bridge ***********
DEBUG [Importer] Applying the following configuration:  { dependencies:
   [ { name: 'aurelia-kendoui-bridge',
       path: '../node_modules/aurelia-kendoui-bridge',
       resources: [],
       main: 'index' } ] }
INFO [Metadata] Adding/removing dependencies to the 'vendor-bundle.js' bundle
INFO [Metadata] The 'aurelia-kendoui-bridge' dependency has been added.
INFO [Metadata] vendor-bundle.js has been configured.

DEBUG [Metadata] No bundles need to be created
DEBUG [Metadata] No tasks have to be created
INFO [Tutorial] *********** Tutorial ***********
INFO [Tutorial] Are you the maintainer of aurelia-kendoui-bridge and would you like to define a tutorial that is displayed here?
INFO [Tutorial] In order to do so you can add an "aurelia"."import"."tutorial" section to the package.json of aurelia-kendoui-bridge. This can be set to an array of strings.
INFO [Tutorial] *********** Importing the module ***********
INFO [Tutorial] The following import statements are possible:
INFO [Tutorial] import 'aurelia-kendoui-bridge';
INFO [Tutorial] import aurelia-kendoui-bridge from 'aurelia-kendoui-bridge';
INFO [Tutorial] import * as aurelia-kendoui-bridge from 'aurelia-kendoui-bridge';
INFO [Tutorial] We are looking into ways to detect what is the right one
INFO [Tutorial] *********** End of tutorial ***********
INFO [Importer] ---------------------------------------------------------
```
**What configuration did the importer add to aurelia.json?**
```
          {
            "name": "aurelia-kendoui-bridge",
            "path": "../node_modules/aurelia-kendoui-bridge",
            "resources": [],
            "main": "index"
          }
```
**What code was used to test whether the package is usable?**

**Does it work?**

**In case of failure, what is the expected configuration?**
